//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ink_Canvas_Better.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ink_Canvas_Better.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cursor 的本地化字符串。
        /// </summary>
        public static string Cursor {
            get {
                return ResourceManager.GetString("Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eraser 的本地化字符串。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ExitPPT {
            get {
                return ResourceManager.GetString("ExitPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experimental Features 的本地化字符串。
        /// </summary>
        public static string ExperimentalFeatures {
            get {
                return ResourceManager.GetString("ExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlighter 的本地化字符串。
        /// </summary>
        public static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cu&apos;cu 的本地化字符串。
        /// </summary>
        public static string Magnifier {
            get {
                return ResourceManager.GetString("Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pencil 的本地化字符串。
        /// </summary>
        public static string Pencil {
            get {
                return ResourceManager.GetString("Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick 的本地化字符串。
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PPT 的本地化字符串。
        /// </summary>
        public static string PPT {
            get {
                return ResourceManager.GetString("PPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ink Canvas Better 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ink Canvas Better Setting 的本地化字符串。
        /// </summary>
        public static string SettingWindowTitle {
            get {
                return ResourceManager.GetString("SettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shape 的本地化字符串。
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup and Update 的本地化字符串。
        /// </summary>
        public static string StartupAndUpdate {
            get {
                return ResourceManager.GetString("StartupAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke thickness 的本地化字符串。
        /// </summary>
        public static string StrokeThickness {
            get {
                return ResourceManager.GetString("StrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch 的本地化字符串。
        /// </summary>
        public static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
